import type { Bike, DealerAdapter } from "./types";

const demoBikes: Bike[] = [
  {
    name: "Cube Touring Hybrid ONE 625",
    brand: "Cube",
    category: "E-Bike",
    price: 2799,
    dealer: "Fahrrad XXL",
    dealerUrl: "https://www.fahrrad-xxl.de/cube-touring-hybrid-one-625",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Cube+E-Bike",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Canyon Roadlite CF 7",
    brand: "Canyon",
    category: "Rennrad",
    price: 1899,
    dealer: "Canyon Direct",
    dealerUrl: "https://www.canyon.com/de-de/roadlite-cf-7",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Canyon+Rennrad",
    availability: "2-3 Wochen",
  },
  {
    name: "Kalkhoff Endeavour 5.B Move+",
    brand: "Kalkhoff",
    category: "E-Bike",
    price: 3499,
    dealer: "Lucky Bike",
    dealerUrl: "https://www.lucky-bike.de/kalkhoff-endeavour-5b-move-plus",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Kalkhoff+E-Bike",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Stevens Trekking E-14 Gent",
    brand: "Stevens",
    category: "Trekking",
    price: 3199,
    dealer: "Fahrrad XXL",
    dealerUrl: "https://www.fahrrad-xxl.de/stevens-trekking-e-14",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Stevens+Trekking",
    availability: "4-6 Wochen",
  },
  {
    name: "Bergamont Revox 3",
    brand: "Bergamont",
    category: "Mountainbike",
    price: 799,
    dealer: "Lucky Bike",
    dealerUrl: "https://www.lucky-bike.de/bergamont-revox-3",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Bergamont+MTB",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Specialized Diverge E5",
    brand: "Specialized",
    category: "Gravel",
    price: 1499,
    dealer: "Bike-Discount",
    dealerUrl: "https://www.bike-discount.de/specialized-diverge-e5",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Specialized+Gravel",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Puky Cyke 20-3",
    brand: "Puky",
    category: "Kinder",
    price: 399,
    dealer: "Lucky Bike",
    dealerUrl: "https://www.lucky-bike.de/puky-cyke-20-3",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Puky+Kinder",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Giant Explore E+ 1 Pro GTS",
    brand: "Giant",
    category: "E-Bike",
    price: 3899,
    dealer: "Fahrrad XXL",
    dealerUrl: "https://www.fahrrad-xxl.de/giant-explore-e-plus-1",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Giant+E-Bike",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Scott Scale 970",
    brand: "Scott",
    category: "Mountainbike",
    price: 1149,
    dealer: "Bike-Discount",
    dealerUrl: "https://www.bike-discount.de/scott-scale-970",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Scott+MTB",
    availability: "2-3 Werktage",
  },
  {
    name: "Trek Domane SL 5",
    brand: "Trek",
    category: "Rennrad",
    price: 2999,
    dealer: "Fahrrad XXL",
    dealerUrl: "https://www.fahrrad-xxl.de/trek-domane-sl-5",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Trek+Rennrad",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Gazelle Chamonix C7 HMS",
    brand: "Gazelle",
    category: "City",
    price: 1699,
    dealer: "Lucky Bike",
    dealerUrl: "https://www.lucky-bike.de/gazelle-chamonix-c7",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Gazelle+City",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Haibike AllMtn 6",
    brand: "Haibike",
    category: "E-Bike",
    price: 4599,
    dealer: "Bike-Discount",
    dealerUrl: "https://www.bike-discount.de/haibike-allmtn-6",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Haibike+E-MTB",
    availability: "4-5 Werktage",
  },
  {
    name: "Tern GSD S10 LR",
    brand: "Tern",
    category: "Cargo",
    price: 4999,
    dealer: "Fahrrad XXL",
    dealerUrl: "https://www.fahrrad-xxl.de/tern-gsd-s10",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Tern+Cargo",
    availability: "6-8 Wochen",
  },
  {
    name: "Merida Scultura 4000",
    brand: "Merida",
    category: "Rennrad",
    price: 1999,
    dealer: "Bike-Discount",
    dealerUrl: "https://www.bike-discount.de/merida-scultura-4000",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=Merida+Rennrad",
    availability: "Sofort verfuegbar",
  },
  {
    name: "KTM Macina Gran 710",
    brand: "KTM",
    category: "E-Bike",
    price: 3299,
    dealer: "Lucky Bike",
    dealerUrl: "https://www.lucky-bike.de/ktm-macina-gran-710",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=KTM+E-Bike",
    availability: "Sofort verfuegbar",
  },
  {
    name: "Riese und Mueller Load 75",
    brand: "Riese",
    category: "Cargo",
    price: 5999,
    dealer: "Radwelt",
    dealerUrl: "https://www.radwelt-shop.de/riese-mueller-load-75",
    imageUrl: "https://placehold.co/400x300/e2e8f0/64748b?text=RM+Cargo",
    availability: "Auf Anfrage",
  },
];

export class DemoAdapter implements DealerAdapter {
  name = "Demo";

  async fetchBikes(): Promise<Bike[]> {
    await new Promise((resolve) => setTimeout(resolve, 200));
    return demoBikes;
  }
}
